package com.senai.tcc.components;

public class EmailHtmlModelo {
	
	
	public static String getRedefinirSenhaTemplate(String usrNome, String codigoRecuperacao) {
		return String.format("<!DOCTYPE html>"
                + "<html>"
                + "<head>"
                + "    <meta charset=\"UTF-8\">"
                + "    <title>Redefinição de Senha</title>"
                + "    <style>"
                + "        body {"
                + "            font-family: Arial, sans-serif;"
                + "        }"
                + "        .container {"
                + "            max-width: 600px;"
                + "            margin: 20px auto;"
                + "            padding: 20px;"
                + "            border: 1px solid #000;"
                + "            box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;"
                + "            border-radius: 5px;"
                + "            background: #4CAF50;"
                + "        }"
                + "        .header, .footer {"
                + "            background-color: #4CAF50;"
                + "            padding: 10px;"
                + "            text-align: center;"
                + "            margin-bottom: 20px;"
                + "        }"
                + "        .content {"
                + "            padding: 20px;"
                + "        }"
                + "        .logo-container {"
                + "            display: flex;"
                + "            align-items: center;"
                + "            justify-content: center;"
                + "            margin-bottom: 20px;"
                + "        }"
                + "        .logo {"
                + "            margin-right: 10px;"
                + "        }"
                + "        #logo-nome {"
                + "            font-size: 26px;"
                + "            font-weight: bold;"
                + "            color: black;"
                + "            margin-top: 10px;"
                + "            text-align: center;"
                + "        }"
                + "        #codigo {"
                + "            color: beige;"
                + "        }"
                + "        p {"
                + "            color: white;"
                + "        }"
                + "    </style>"
                + "</head>"
                + "<body>"
                + "    <div class=\"container\">"
                + "        <div class=\"header\">"
                + "            <h2>Redefinição de Senha</h2>"
                + "        </div>"
                + "        <div class=\"content\">"
                + "            <p>Olá %s,</p>"
                + "            <p>Este é o seu código de redefinição de senha: <strong style=\"color: black;\">%s</strong></p>"
                + "            <p>Se você não solicitou uma redefinição de senha, por favor, ignore este e-mail ou entre em contato conosco"
                + "                se tiver alguma dúvida.</p>"
                + "        </div>"
                + "        <div class=\"logo-container\">"
                + "            <img src=\"https://i.ibb.co/d5MGdpH/Odin-Logo.png\" alt=\"Logo do Sistema\" class=\"logo\" width=\"150\">"
                + "            <span id=\"logo-nome\">ODIN</span>"
                + "        </div>"
                + "    </div>"
                + "</body>"
                + "</html>"
				, usrNome, codigoRecuperacao
				);
	}
}
